### ISSUE TITLE
Phrase - missing getters and setters

### ISSUE THREAD

**Issue by einstein07** [AdeebNqo/NguniTextGeneration#10]
Get: 
1. Identification string
2. Next part

Set:
1. Identification string
2. Next part

**Comment by AdeebNqo** [comment]
The string assigned to each object in the serialised file can be retrieved via `getSerialisedName` (see commit: 87fd9ceecf76df6cded65374643c151ec4780e2a). Please note that the old `getIdentification` and `setIdentification` functions that were available in some of the models have been deprecated.

The Phrase class is a subclass of `TemplatePortion` hence already has the `setNextPart` and `getNextPart` method via inheritance.
