### ISSUE TITLE
Polymorphic word - missing getters and setters

### ISSUE THREAD

**Issue by einstein07** [AdeebNqo/NguniTextGeneration#11]
Get:
1. Relies on
2. First part
3. Last part
4. Next part

Set:
1. Relies on
2. First part
3. Last part
4. Next part

**Comment by AdeebNqo** [comment]
The PolymorphicWord` extends the `Chimera`, which extends `Word` and it extends `TemplatePortion`; hence it already has a `getNextPart` method.

I've also introduced a `getItemsItReliesOn` method (see commit be8dc3ee837a1750a6abdab555857a55a135f3b4). Other methods that are already available for this are `doesReliesOnSomething` for determing whether a `PolymorphicWord` relies on something and `reliesOn` for checking whether it relies on a specific object. In the same commit, I've introduced `getFirstItem` and `getLastItem`
