### ISSUE TITLE
Copula - missing getters and setters

### ISSUE THREAD

**Issue by einstein07** [AdeebNqo/NguniTextGeneration#12]
It seems for the copula the label attribute is interchangeable with the value attribute? - i.e. the getValue method will return whatever value stored in the value attribute but if the value attribute is empty it will return whatever value is stored in the label attribute, so I guess this is fine (the label attribute does not have a set nor a get of its own). However, the below methods are still missing:
Get:
1. Next part
Set:
1. Next part

**Comment by AdeebNqo** [comment]
The copula class is a subclass of `TemplatePortion` hence already has the `setNextPart` and `getNextPart` method via inheritance.
