### ISSUE TITLE
Unimorphic word - missing getters and setters

### ISSUE THREAD

**Issue by einstein07** [AdeebNqo/NguniTextGeneration#14]
Get:
1. Next part
Set:
1. Next part

**Comment by AdeebNqo** [comment]
The `getNextPart` and `setNextPart` methods are already available as a result of its superclass `TemplatePortion`

**Comment by einstein07** [comment]
It seems there is no setter for the value attribute - i.e. one can get the value but can't set it.

**Comment by AdeebNqo** [comment]
Fixed. See commit 1bad3cc497032c5fe8cf44c71724c2c4152aa2d6
