### ISSUE TITLE
No Class Def Found Exception

### ISSUE THREAD

**Issue by einstein07** [AdeebNqo/NguniTextGeneration#18]
Following the changes that were made to the Nguni Text Generation repo code, I built new artifacts for the various modules employed by the ToCTeditor - specifically, when we attempt to parse a template now using the below piece of code:
  
![code](https://user-images.githubusercontent.com/53013773/145423451-b19fa0b7-1990-41c0-8805-bf336d08e39a.png)

we get the error below:
![error](https://user-images.githubusercontent.com/53013773/145423806-628d4980-b1e3-4cde-af35-71dd11107281.png)

I should add that when we run the main file in the Nguni Text Generation repo, this error does not occur. Any ideas what could be wrong here?

**Comment by AdeebNqo** [comment]
This is weird. If it works via the main file then I reckon that the jena packages are not being exported by the template parsing module.

I will look into this later today when I am on my Linux box.

**Comment by AdeebNqo** [comment]
I've pushed a new branch on the ToCTeditor (see https://github.com/einstein07/ToCTeditor/tree/fixing_makefile_and_testing_newjar). Please review it and fix the error pertaining to the DataModel.java class so I can confirm that my fix for this issue works.

**Comment by AdeebNqo** [comment]
The GrammarEngineNguni jar was including the wrong Apache Jena version. This has been updated.
