### ISSUE TITLE
It seems there is no setter for the value attribute - i.e. one can get the value but can't set it.

### ISSUE THREAD

**Issue by einstein07** [AdeebNqo/NguniTextGeneration#20]
It seems there is no setter for the value attribute - i.e. one can get the value but can't set it.

_Originally posted by @einstein07 in https://github.com/AdeebNqo/NguniTextGeneration/issues/14#issuecomment-994866082_

**Comment by AdeebNqo** [comment]
see commit 1bad3cc497032c5fe8cf44c71724c2c4152aa2d6
