### ISSUE TITLE
Polymorphic word - missing word-portions setter

### ISSUE THREAD

**Issue by einstein07** [AdeebNqo/NguniTextGeneration#21]
There is a getter for the word portions, however, there is no means of adding a new word portion(s) yet the gui allows for this functionality.

**Comment by AdeebNqo** [comment]
The most recent commit (7e44fdef7930f10b7856b9028c69be974ea0ee1a) fixes this issue. Specificaly, I've added a method for adding a morpheme (i.e., addMorpheme(InternalSlotRootAffix someMorpheme)), removing a morpheme by value (i.e., removeMorpheme(InternalSlotRootAffix someMorpheme)), and a removal of morpheme by index (i.e., removeMorpheme(int indexOfMorpheme))
