### ISSUE TITLE
Add setValue function for Unimorphicord, Phrase, Puntuation 

### ISSUE THREAD

**Issue by einstein07** [AdeebNqo/NguniTextGeneration#24]
@AdeebNqo  Please add set-value-functionality for the above template portions

**Comment by AdeebNqo** [comment]
The UnimorphicWord, Phrase, and Punctuation all have constructors that allow the setting of values. They also have setValue methods. If you cannot find the setValue then its because the jar files of release v1.1 are outdated. I will upload the latest release. Please use that one.
