### ISSUE TITLE
Template validation 

### ISSUE THREAD

**Issue by einstein07** [AdeebNqo/NguniTextGeneration#26]
I was wondering if there is validation functionality of a newly created template for this model (for instance created using the ToCTEditor)?

**Comment by AdeebNqo** [comment]
There is a module that can be used for that. Later today, I will post a snippet for how to validate a template l

**Comment by AdeebNqo** [comment]
You have to create an error detector and pass it the location of the version of ToCT that you're using in the following way:

```TemplateErrorDetector logicalErrDetector = new TemplateErrorDetector(...);```

For instance, if the we have to use a version found in the temporary folder `/tmp/ToCT/ToCT.owl` then the code would be:

```TemplateErrorDetector logicalErrDetector = new TemplateErrorDetector("/tmp/ToCT/ToCT.owl");```

Then you can use the `TemplateErrorDetector` to see if a template is consitent by either using `hasInconsistencies` or `getConsistencyReport`. There are also versions of the methods that you can use if you have multiple templates.

If the template is saved in a file, even if its temporary, then you could use the following code to detect any problems:

```
//error detection
TemplateValidationReport report = logicalErrDetector.getConsistencyReport(getTemplateFilePath());

//displaying the problem to the console
if (report.isInconsistent()) {
	System.out.println("Problem found.")
	System.out.println(report.toString());
}
```
