### ISSUE TITLE
setValue & getNextPart methods in "UnimorphicAffix" class

### ISSUE THREAD

**Issue by einstein07** [AdeebNqo/NguniTextGeneration#28]
@AdeebNqo  could you please add the above methods to the said class? - thanks.

**Comment by AdeebNqo** [comment]
They have been added. Please see the latest commit and release.

**Comment by einstein07** [comment]
I can see the commit - however, the latest release is from 16 days ago @AdeebNqo 

Please double-check - thanks!

**Comment by AdeebNqo** [comment]
If you go to https://github.com/AdeebNqo/NguniTextGeneration/releases, you will see the latest version (from 5 days ago).

Please note that the getNextPart function has been renamed to getNextMorphPart in the case of morphemes and getNextWordPart in the case of word level item
