### ISSUE TITLE
Openning an existing template

### ISSUE THREAD

**Issue by einstein07** [AdeebNqo/NguniTextGeneration#7]
When attempting to open an existing template the following lines of code are written/executed:
![existing template](https://user-images.githubusercontent.com/53013773/144591309-6d29c0f4-5b31-40a4-8ac3-a4cb011f4ecc.png)

However, the template is never read, instead we encounter the error below:
![templatereading error](https://user-images.githubusercontent.com/53013773/144591376-f924ec2a-a879-457e-8fdb-8b577bd35360.png)

The approach for opening an existing template was adapted from the ontology verbaliser sorce code.

**Comment by AdeebNqo** [comment]
The parser only uses the `templateName' variable. It does not actually deduce the template name from the `templatePath'. The most recent commit (6b9e98546907e4432434928a8695817c046d4d06) solves this problem by producing an informative message as part of the message.
