### ISSUE TITLE
Slot - missing getters and setters

### ISSUE THREAD

**Issue by einstein07** [AdeebNqo/NguniTextGeneration#8]
Set:
1. Label
2. Next part

Get:
1. Next part 
2. You can set "Relies on labels" but you cannot get them

**Comment by AdeebNqo** [comment]
The most recent commit (22e850c74b6e2c1ce2ea62852d705c3f82acdb1c) addresses this problem. Specifically, I introduced `getReliesOnLabels` in the `Slot` class. I also introduced a way of retrieving the next part. When going over the portions of a template or polymorphic word, you need to call `getNextPart` to get the part.
