### ISSUE TITLE
Punctuation - missing getters and setters

### ISSUE THREAD

**Issue by einstein07** [AdeebNqo/NguniTextGeneration#9]
Set:
1. Identification string
2. Value

Get:
1. Identification string
2. Value

**Comment by AdeebNqo** [comment]
The string assigned to each object in the serialised file can be retrieved via `getSerialisedName` (see commit: 87fd9ceecf76df6cded65374643c151ec4780e2a). Please note that the old `getIdentification` and `setIdentification` functions that were available in some of the models have been deprecated.

The value get be retrieved via  `toString`. I've also added a  `getValue` (see 356adb6ab070d6469f638e2979e4b0c8d2207317)
